Discretization and binning

In [1]:
import pandas as pd
import numpy as np

In [2]:
results = np.random.randint(100, size = 30)

In [3]:
results

array([56, 47, 85, 39, 93, 55, 71, 50, 34, 61, 93, 57, 77, 67, 64, 77, 94,
       22, 31, 94, 36,  4, 57, 75, 14, 92, 27, 53, 64, 55])

In [4]:
# also for the bins you can write a list or array of values
pd.cut(results, 4)

[(49.0, 71.5], (26.5, 49.0], (71.5, 94.0], (26.5, 49.0], (71.5, 94.0], ..., (71.5, 94.0], (26.5, 49.0], (49.0, 71.5], (49.0, 71.5], (49.0, 71.5]]
Length: 30
Categories (4, interval[float64]): [(3.91, 26.5] < (26.5, 49.0] < (49.0, 71.5] < (71.5, 94.0]]

In [5]:
pd.cut(results, 4).categories

IntervalIndex([(3.91, 26.5], (26.5, 49.0], (49.0, 71.5], (71.5, 94.0]],
              closed='right',
              dtype='interval[float64]')

In [6]:
pd.cut(results, 4).codes

array([2, 1, 3, 1, 3, 2, 2, 2, 1, 2, 3, 2, 3, 2, 2, 3, 3, 0, 1, 3, 1, 0,
       2, 3, 0, 3, 1, 2, 2, 2], dtype=int8)

In [7]:
# you can label the categories by using labels parameter
pd.cut(results, 4, labels = 'bad good great excellent'.split())

[great, good, excellent, good, excellent, ..., excellent, good, great, great, great]
Length: 30
Categories (4, object): [bad < good < great < excellent]

q cut makes sure bins are equal

In [8]:
cat = pd.qcut(results, 4)

In [9]:
cat

[(41.0, 57.0], (41.0, 57.0], (76.5, 94.0], (3.999, 41.0], (76.5, 94.0], ..., (76.5, 94.0], (3.999, 41.0], (41.0, 57.0], (57.0, 76.5], (41.0, 57.0]]
Length: 30
Categories (4, interval[float64]): [(3.999, 41.0] < (41.0, 57.0] < (57.0, 76.5] < (76.5, 94.0]]

removing outliers

In [10]:
rand = pd.DataFrame(np.random.randint(1000, size =(500,3)), columns = 'A B C'.split())

In [11]:
rand

A    B    C
0    372  685    4
1    962  924  452
2    780  364  476
3    157  798  509
4    165  397  433
..   ...  ...  ...
495  983  510  819
496  838   69   51
497  714  567  597
498  210  384  794
499  939  272   16

[500 rows x 3 columns]

In [12]:
rand.describe()

A           B           C
count  500.000000  500.000000  500.000000
mean   496.076000  518.542000  499.772000
std    276.253736  279.976073  292.219418
min      3.000000    2.000000    1.000000
25%    280.250000  274.000000  245.750000
50%    496.500000  524.000000  504.500000
75%    713.250000  746.750000  765.250000
max    998.000000  996.000000  993.000000

In [13]:
# any() function returns True value in an iterable

rand[(np.abs(rand) > (3.2*rand.std())).any(1)]

A    B    C
1    962  924  452
10   950  420  693
11   938  395  254
20   570  980  792
23   546  761  969
..   ...  ...  ...
475   45  204  946
481  996  845  173
485  939   37   42
495  983  510  819
499  939  272   16

[128 rows x 3 columns]

In [14]:
# permutation
# arranges set of values using the np.random.permutation()

np.random.permutation(10)

array([5, 7, 8, 2, 9, 4, 6, 3, 1, 0])

In [15]:
df = pd.DataFrame(np.arange(50).reshape(25,2), columns = ['a', 'b'])

In [16]:
df

a   b
0    0   1
1    2   3
2    4   5
3    6   7
4    8   9
5   10  11
6   12  13
7   14  15
8   16  17
9   18  19
10  20  21
11  22  23
12  24  25
13  26  27
14  28  29
15  30  31
16  32  33
17  34  35
18  36  37
19  38  39
20  40  41
21  42  43
22  44  45
23  46  47
24  48  49

In [17]:
#rearrange the numbers
df = df.take(np.random.permutation(25))

In [18]:
df

a   b
4    8   9
22  44  45
0    0   1
12  24  25
17  34  35
3    6   7
15  30  31
14  28  29
9   18  19
5   10  11
6   12  13
1    2   3
16  32  33
8   16  17
19  38  39
10  20  21
13  26  27
18  36  37
2    4   5
20  40  41
21  42  43
11  22  23
24  48  49
23  46  47
7   14  15